DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/urls.py
from django.urls import path,include
# from DocOrgnizer.views import dashboard,register,CustomerSignUpView,DeliverySignUpView, about, signup, StoreSignUpView,CustomPasswordResetView, PasswordResetDoneView, userprofile#,SignUpView,StoreSignUpView,DeliverySignUpView
from DocOrgnizer.views import  sign_up , home_view, about_us ,activate  , forgot_password, reset_password,login_view

urlpatterns = [
    # path("", dashboard, name="dashboard"),
    # path('accounts/signup/customer/', CustomerSignUpView, name="customer_signup"),
    # path("accounts/signup/", signup , name="signup"),
    # path('accounts/signup/store/', StoreSignUpView, name="store_signup"),
    # path('accounts/signup/delivery/', DeliverySignUpView, name="delivery_signup"),
    # path("accounts/resetPassword/",  CustomPasswordResetView.as_view(), name="resetPassword"),
    # path("accounts/resetPassword/done", PasswordResetDoneView.as_view(), name="resetPasswordDone"),
    # path("accounts/", include("django.contrib.auth.urls")),
    # path("accounts/login/userProfile/",userprofile, name="userProfile"),
    # #path('oauth/', include('social_django.urls', namespace="social")),
    # path("register/", register, name="register"),
    # path("about/",about, name="about"),
    #path('',homepage,name='homepage'),
    # urls.py
    path('', home_view, name='home'),
    path('about/', about_us, name='about'),
    path('login/', login_view, name='login'), 
    path('signup/',sign_up,name='signup'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('forgoturpassword/', forgot_password, name='forgoturpassword'),
    path('reseturpassword/<uidb64>/<token>', reset_password, name='reseturpassword'),
    #path('login', login, name='login'),
    #path('logout', logout, name='logout'),
] 


DocOrgFinalOne/DocOrgFinalOne/DocOrgnizerMaria/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("", include("DocOrgnizer.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/models.py
from cgi import FieldStorage
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import RegexValidator
import uuid
import re
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager,PermissionsMixin

# Create your models here.
# class User(AbstractUser):
#     username = models.CharField(max_length=30, unique=True)
#     email = models.EmailField(unique=True)  # Added email field
#     national_id = models.CharField(max_length=9, unique=True)
#     image_url = models.URLField(blank=True, null=True)
#     # REQUIRED_FIELDS = ('user',)

#     # user = models.OneToOneField(User, related_name='profile', unique=True)
#     def __str__(self):
#         return self.get_username()


# class CustomUser(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

#     def __str__(self):
#         return self.user.get_username()

# models.py
# from django.db import models

# models.py
from django.db import models
from django.utils.crypto import get_random_string

# models.py


class UserProfile(AbstractUser):
    full_name = models.CharField(max_length=255, unique=True)
    national_id = models.PositiveIntegerField(unique=True)
    email = models.EmailField(unique=True)
    national_id_photo = models.ImageField(upload_to='national_id_photos/')
    # is_active = models.BooleanField(default=False) 
    # confirmation_token = models.CharField(max_length=32, null=True, blank=True)   
    # Remove unwanted fields
    username=None
    first_name = None
    last_name = None
    USERNAME_FIELD = 'full_name'
    REQUIRED_FIELDS = ['national_id','email']
    
    # def save(self, *args, **kwargs):
    #     if not self.confirmation_token:
    #         self.confirmation_token = get_random_string(length=32)
    #     super().save(*args, **kwargs)

    def __str__(self):
        return self.full_name



DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/forms.py
# forms.py
from django import forms
import os
from django.core.exceptions import ValidationError
from .models import UserProfile
from django.core.validators import validate_email
from PIL import Image
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate

from .validators import (
    IsEntireAlphaPasswordValidator,
    HasUpperCasePasswordValidator,
    HasLowerCasePasswordValidator,
    HasNumberPasswordValidator,
    HasSpecialCharacterPasswordValidator,
)
class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = UserProfile
        fields = ['full_name', 'national_id', 'email', 'national_id_photo', 'password', 'confirm_password']
    def clean_full_name(self):
        full_name = self.cleaned_data['full_name']
        if not all(char.isalpha() or char.isspace() for char in full_name):
            raise ValidationError('Full name must contain only letters and spaces.')
        return full_name

    def clean_national_id(self):
        national_id = self.cleaned_data['national_id']
        if len(str(national_id)) != 9 or not national_id > 0:
            raise ValidationError('National ID must be a 9-digit positive number.')
        return national_id

    def clean_password(self):
        password = self.cleaned_data.get('password')
        validators = [
            IsEntireAlphaPasswordValidator(),
            HasUpperCasePasswordValidator(),
            HasLowerCasePasswordValidator(),
            HasNumberPasswordValidator(),
            HasSpecialCharacterPasswordValidator(),
        ]

        for validator in validators:
            validator.validate(password)

        return password
    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            # Validate email format
            validate_email(email)
        except ValidationError:
            raise ValidationError('Invalid email address.')

        # Check if the email already exists in the database
        if UserProfile.objects.filter(email=email).exists():
            raise ValidationError('Email is already in use.')

        return email
    def clean_national_id_photo(self):
        national_id_photo = self.cleaned_data['national_id_photo']

        # Check if a file was uploaded
        if not national_id_photo:
            raise ValidationError('No image selected.')

        # Validate that the file is an image (you may need to install Pillow for this)
        try:
            img = Image.open(national_id_photo)
        except Exception as e:
            raise ValidationError(f'Invalid image file: {e}') from e
        return national_id_photo

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        full_name = cleaned_data.get('full_name')
        national_id = cleaned_data.get('national_id')
        if not full_name or not national_id:
        # If earlier validations failed, don't proceed with further checks
            return cleaned_data
        file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'civilregistry.txt')

        with open(file_path, 'r') as file:
            lines = file.readlines()
            matching_line = None

            for line in lines:
                attributes = line.strip().split(',')
                print(f"User Input: {full_name}, {national_id}")
                print(f"File Data: {attributes[0]}, {attributes[1]}")
                # Compare case-insensitive and strip whitespaces
                if full_name.lower().strip() == attributes[0].lower().strip() and str(national_id) == attributes[1]:
                    matching_line = line
                    break
            if matching_line is None:
                print("Invalid Credentials. Do not match with civil registry.")
                raise ValidationError("Invalid Credentials. Do not match with civil registry.", code='invalid_credentials')               

        if password and confirm_password and password != confirm_password:
            raise ValidationError('Passwords do not match.', code='password_mismatch')

        return cleaned_data

class ForgotPasswordForm(PasswordResetForm):
    email = forms.EmailField(label='Enter your email to reset password', max_length=254)

    def clean_email(self):
        email = self.cleaned_data['email']
        User = get_user_model()

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            raise forms.ValidationError("This email address is not associated with any account .")

        if not user.is_active:
            raise forms.ValidationError("Account not active or other validation issue.")

        return email
    
class PasswordResetForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean_password(self):
        password = self.cleaned_data.get('password')
        validators = [
            IsEntireAlphaPasswordValidator(),
            HasUpperCasePasswordValidator(),
            HasLowerCasePasswordValidator(),
            HasNumberPasswordValidator(),
            HasSpecialCharacterPasswordValidator(),
        ]

        for validator in validators:
            validator.validate(password)

        return password

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise ValidationError('Passwords do not match.', code='password_mismatch')

        return cleaned_data
    
    
    
    
from DocOrgnizer.models import UserProfile    
from django.utils.translation import gettext_lazy as _ 
from django.db.models import Q
   

       
class SignInViaEmailOrUsernameForm(forms.Form):
    email_or_username = forms.CharField(label=_('Email or Username'))
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput)
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        email_or_username = cleaned_data.get('email_or_username')

        user = UserProfile.objects.filter(Q(full_name__iexact=email_or_username) | Q(email__iexact=email_or_username)).first()
        if not user:
            raise ValidationError(_('You entered an invalid username or password.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

    
        if not user.check_password(password):
            raise ValidationError(_('You entered an invalid username or password.'))

    
        return cleaned_data

    
   



DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/templates/registreation/about.html
<!-- DocOrgnizer/templates/registration/base.html -->
{% extends 'home.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css">
    <style>
        .developer-box {
            background-color: #f4f4f4;
            padding: 20px;
            margin-bottom: 20px;
        }

        .developer-image {
            max-width: 90%;
            height: auto;
            border-radius: 8px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="columns">
            <!-- Developer 1 -->
            <div class="column is-one-third">
                <div class="developer-box">
                    <img src="t1.jpeg" alt="Developer 1" class="developer-image">
                    <p>
                        Maria Abu Samoor, Computer Systems Engineering steudent. Jane is passionate about creating beautiful and
                        user-friendly interfaces. With years of experience, she brings creativity and innovation
                        to every project.
                    </p>
                </div>
            </div>

            <!-- Developer 2 -->
            <div class="column is-one-third">
                <div class="developer-box">
                    <img src="t.jpeg" alt="Developer 2" class="developer-image">
                    <p>
                        John Smith is our backend guru. He loves solving complex problems and optimizing
                        server-side processes. John's expertise ensures our applications run smoothly and efficiently.
                    </p>
                </div>
            </div>

            <!-- Developer 3 -->
            <div class="column is-one-third">
                <div class="developer-box">
                    <img src="t.jpeg" alt="Developer 3" class="developer-image">
                    <p>
                        Mary Johnson, our full-stack developer, is a versatile talent. She enjoys working on both
                        frontend and backend aspects, creating seamless and integrated solutions for our users.
                    </p>
                </div>
            </div>
        </div>
    </div>

</body>
</html>
{% endblock %}

DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/templates/registreation/forgoturpassword.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forget Your Password</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css">
</head>

<body>
    <div class="container">
        <div class="column is-4 is-offset-4">
            <div class="box has-background-light">
                <form method="POST">
                    {% csrf_token %}
                    {% for message in messages %}
                            <p class="help is-danger">{{ message|safe  }}</p>
                    {% endfor %}
                    {% if form.non_field_errors %}
                        <div class="notification is-danger">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}

                    <div class="field">
                        <label class="label" style="color: #48c78e;">Enter your email to reset password</label>
                        <div class="control">
                            <input class="input is-medium" type="email" name="email" placeholder="Enter your email">
                        </div>
                        {% if form.email.errors %}
                            <p class="help is-danger">{{ form.email.errors }}</p>
                        {% endif %}
                    </div>

                    <div class="field">
                        <button class="button is-success is-fullwidth is-medium">Send Email</button>

                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>
{% endblock %}

DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/templates/registreation/logout.html
{% extends 'base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3"  style="min-height:65vh;">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/templates/registreation/reseturpassword.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forget Your Password</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css">
    <style>
        .password-policy-tooltip {
            position: relative;
            display: inline-block;
            cursor: pointer;
        }

        .password-policy-tooltip:hover .password-policy-tooltip-text {
            display: block;
        }

        .password-policy-tooltip-text {
            display: none;
            position: absolute;
            background-color: #d4d4d4;
            color: black;
            padding: 5px;
            border-radius: 4px;
            z-index: 1;
            bottom: 125%;
            left: 0;
            width: 350px;
        }

        .password-policy-tooltip-text p {
            margin: 5px 0;
        }

        /* Apply "control" styles to "password-policy-tooltip" */
        .password-policy-tooltip .control {
            width: 100%;
            box-sizing: border-box;
            display: flex;
            align-items: stretch;
        }
        .container{
        height: 70vh;
        display: flex;
        flex-direction: column;
        justify-content: center; 
        }
        .password-policy-tooltip .input {
            flex: 1;
            margin-right: 7em; /* Adjust margin if needed */
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="column is-4 is-offset-4">
            <div class="box has-background-light">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Display global form errors -->
                    {% for error in form.non_field_errors %}
                        <p class="notification is-danger">{{ error }}</p>
                    {% endfor %}
                    <div class="field">
                        <label class="label" for="id_password">New Password</label>
                        <div class="control password-policy-tooltip">
                            <input class="input is-medium {% if form.password.errors %}is-danger{% endif %}" 
                                placeholder="Enter your password" 
                                name="{{ form.password.name }}"
                                type="{{ form.password.field.widget.input_type }}"
                                id="{{ form.password.id_for_label }}">
                            <div class="password-policy-tooltip-text">
                                <p>• Your password can't be too similar to your other personal information.</p>
                                <p>• Your password must contain at least 8 characters.</p>
                                <p>• Your password can't be a commonly used password.</p>
                                <p>• Your password can't be entirely numeric.</p>
                                <p>• Your password must contain at least one uppercase, one lowercase, and one special character.</p>
                            </div>
                            <!-- Display field-specific errors -->
                            {% for error in form.password.errors %}
                                <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                            
                            {% for validator in form.password.validators %}
                                {% for error in validator.errors %}
                                    <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            {% endfor %}
                        </div>
                    </div>

                    <div class="field">
                        <label class="label" for="id_confirm_password">Confirm Password</label>
                        <div class="control">
                            <input class="input is-medium {% if form.confirm_password.errors %}is-danger{% endif %}" 
                                placeholder="Confirm your password" 
                                name="{{ form.confirm_password.name }}"
                                type="{{ form.password.field.widget.input_type }}"
                                id="{{ form.confirm_password.id_for_label }}">
                            <!-- Display field-specific errors -->
                            {% for error in form.confirm_password.errors %}
                                <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="field">
                        <button class="button is-success is-fullwidth is-medium">Password Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>


</html>
{% endblock %}

DocOrgFinalOne/DocOrgFinalOne/DocOrgnizer/templates/registreation/signup.html
<!-- sign_up.html -->
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css">
    <title>Sign Up</title>
    <style>
        .password-policy-tooltip {
            position: relative;
            display: inline-block;
            cursor: pointer;
        }

        .password-policy-tooltip:hover .password-policy-tooltip-text {
            display: block;
        }

        .password-policy-tooltip-text {
            display: none;
            position: absolute;
            background-color: #d4d4d4;
            color: black;
            padding: 10px;
            border-radius: 4px;
            z-index: 1;
            bottom: 125%;
            left: 0;
            width: 250px;
        }

        .password-policy-tooltip-text p {
            margin: 5px 0;
        }

        /* Apply "control" styles to "password-policy-tooltip" */
        .password-policy-tooltip .control {
            width: 100%;
            box-sizing: border-box;
            display: flex;
            align-items: stretch;
        }
        .container{
        height: 70vh;
        display: flex;
        flex-direction: column;
        justify-content: center; 
        }

        .password-policy-tooltip .input {
            flex: 1;
            margin-right: 7em; /* Adjust margin if needed */
        }
    </style>

</head>
<body>
    <div class="container">
        <div class="column is-4 is-offset-4">
            <div class="box has-background-light">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {# Display custom validation error message #}
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            {% if error.code == 'invalid_credentials' %}
                                <div class="notification is-danger">
                                    <p>{{ error }}</p>
                                </div>
                            {% else %}
                                <div class="notification is-danger">
                                    <p>{{ error }}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <!-- {{ form.non_field_errors }}            -->
                    <div class="field">
                        <label class="label">Full User Name</label>
                        <div class="control">
                            <input class="input is-medium {% if form.full_name.errors %}is-danger{% endif %}" 
                               placeholder="Enter your full name" 
                               name="{{ form.full_name.name }}"
                               value="{{ form.full_name.value|default:'' }}" 
                               type="{{ form.full_name.field.widget.input_type }}" 
                               id="{{ form.full_name.id_for_label }}">
                        </div>
                        {% for error in form.full_name.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>      
                   
                    <div class="field">
                        <label class="label" for="id_national_id">National ID</label>
                        <div class="control">
                            <input class="input is-medium {% if form.national_id.errors %}is-danger{% endif %}" 
                                placeholder="Enter your national ID" 
                                name="{{ form.national_id.name }}"
                                value="{{ form.national_id.value|default:'' }}" 
                                type="{{ form.national_id.field.widget.input_type }}" 
                                id="{{ form.national_id.id_for_label }}">
                        </div>
                        {% for error in form.national_id.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <!-- Email -->
                    <div class="field">
                        <label class="label" for="id_email">Email</label>
                        <div class="control">
                            <input class="input is-medium {% if form.email.errors %}is-danger{% endif %}" 
                                placeholder="Enter your email" 
                                name="{{ form.email.name }}"
                                value="{{ form.email.value|default:'' }}" 
                                type="{{ form.email.field.widget.input_type }}" 
                                id="{{ form.email.id_for_label }}">
                        </div>
                        {% for error in form.email.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                

                    <!-- Password -->
                    <div class="field">
                        <label class="label" for="id_password">Password</label>
                        <div class="control password-policy-tooltip">
                            <input class="input is-medium {% if form.password.errors %}is-danger{% endif %}" 
                                placeholder="Enter your password" 
                                name="{{ form.password.name }}"
                                type="{{ form.password.field.widget.input_type }}" 
                                id="{{ form.password.id_for_label }}">
                                <div class="password-policy-tooltip-text">
                                    <p>• Your password can't be too similar to your other personal information.</p>
                                    <p>• Your password must contain at least 8 characters.</p>
                                    <p>• Your password can't be a commonly used password.</p>
                                    <p>• Your password can't be entirely numeric.</p>
                                    <p>• Your password must contain at least one uppercase, one lowercase, and one special character.</p>
                                </div>
                        </div>
                        {% for error in form.password.errors %}
                            {% if error.code != 'invalid_credentials' %}
                                <p class="help is-danger">{{ error }}</p>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <!-- Confirm Password -->
                    <div class="field">
                        <label class="label" for="id_confirm_password">Confirm Password</label>
                        <div class="control">
                            <input class="input is-medium {% if form.confirm_password.errors %}is-danger{% endif %}" 
                                placeholder="Confirm your password" 
                                name="{{ form.confirm_password.name }}"
                                type="{{ form.confirm_password.field.widget.input_type }}" 
                                id="{{ form.confirm_password.id_for_label }}">
                        </div>
                        {% for error in form.confirm_password.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="field">
                        <label class="label" for="id_national_id_photo">Upload Your ID Image</label>
                        <div class="control">
                            <input class="input is-medium {% if form.national_id_photo.errors %}is-danger{% endif %}" 
                                placeholder="Enter your ID image" 
                                name="{{ form.national_id_photo.name }}"
                                value="{{ form.national_id_photo.value|default:'' }}" 
                                type="{{ form.national_id_photo.field.widget.input_type }}" 
                                id="{{ form.national_id_photo.id_for_label }}"
                                accept=".png, .jpeg, .jpg">
                        </div>
                        {% for error in form.national_id_photo.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>                    
                    <div class="field">
                        <button class="button is-success is-fullwidth is-medium">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock content %}